version: '3.8'

services:
  db:
    build: 
      context: ./database/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=aalonso
      - POSTGRES_PASSWORD=aalonso
    container_name: postgres-db
    hostname: postgres-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database/sql:/sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - default
  
  pg-admin:
    image: dpage/pgadmin4
    container_name: pg-admin-zoomcamp
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    networks:
      - default

networks:
  default:
    name: nt-nyc
