version: '3.8'

services:
  db:
    build: 
      context: ./database/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=aalonso
      - POSTGRES_PASSWORD=aalonso
    container_name: postgres-db
    hostname: postgres-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database/sql:/sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - default
  
  pg-admin:
    image: dpage/pgadmin4
    container_name: pg-admin-zoomcamp
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL : ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - default
  
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
      - ~/Documents/secrets/personal-gcp.json:/home/src/personal-gcp.json
    restart: on-failure:5
    networks:
      - default

networks:
  default:
    name: nt-nyc
