version: 2

sources:
  - name: staging
    database: terrademo-412014
     # For postgres:
      #database: production
    schema: terrademo_dataset

      # loaded_at_field: record_loaded_at
    tables:
      - name: new_green_tripdata
      - name: new_yellow_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}

